# Generated by Django 5.0.7 on 2024-07-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_leave',
            field=models.BooleanField(default=False),
        ),
    ]
