# Generated by Django 5.0.7 on 2024-08-02 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_simplifieddata_month_simplifieddata_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryExcelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='temp_excel/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
